<a href="https://colab.research.google.com/github/venuaravind-14/VAC-Value_Added_Course-AI-ML/blob/main/Day4.1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##EXNO 4.1 (Text_analytics for CHATBOT)



In [ ]:
import pickle
import numpy as np
import tensorflow

In [ ]:
from keras.models import Sequential
from keras.layers import Dense

In [ ]:
with open("/content/train_qa.txt","rb") as fp:
  train_data = pickle.load(fp)

In [ ]:
with open("/content/test_qa.txt","rb") as fp:
  test_data = pickle.load(fp)

In [ ]:
' '.join(train_data[0][0])

'Mary moved to the bathroom . Sandra journeyed to the bedroom .'

In [ ]:
' '.join(train_data[0][1])

'Is Sandra in the hallway ?'

In [ ]:
' '.join(train_data[0][2])

'n o'

In [ ]:
type(test_data)

list

In [ ]:
vocab = set()

In [ ]:
all_data = test_data + train_data

In [ ]:
for story, question, answer in all_data:
  vocab = vocab.union(set(story))
  vocab = vocab.union(set(question))

In [ ]:
vocab.add('no')
vocab.add('yes')

In [ ]:
vocab

{'.',
 '?',
 'Daniel',
 'Is',
 'John',
 'Mary',
 'Sandra',
 'apple',
 'back',
 'bathroom',
 'bedroom',
 'discarded',
 'down',
 'dropped',
 'football',
 'garden',
 'got',
 'grabbed',
 'hallway',
 'in',
 'journeyed',
 'kitchen',
 'left',
 'milk',
 'moved',
 'no',
 'office',
 'picked',
 'put',
 'the',
 'there',
 'to',
 'took',
 'travelled',
 'up',
 'went',
 'yes'}

In [ ]:
vocab_len=len(vocab)+1

In [ ]:
max_story_len = max([len(data[0]) for data in all_data])

In [ ]:
max_story_len

156

In [ ]:
max_question_len = max([len(data[1]) for data in all_data])

In [ ]:
max_question_len

6

In [ ]:
vocab

{'.',
 '?',
 'Daniel',
 'Is',
 'John',
 'Mary',
 'Sandra',
 'apple',
 'back',
 'bathroom',
 'bedroom',
 'discarded',
 'down',
 'dropped',
 'football',
 'garden',
 'got',
 'grabbed',
 'hallway',
 'in',
 'journeyed',
 'kitchen',
 'left',
 'milk',
 'moved',
 'no',
 'office',
 'picked',
 'put',
 'the',
 'there',
 'to',
 'took',
 'travelled',
 'up',
 'went',
 'yes'}

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer=Tokenizer()
vocab_size=len(tokenizer.word_index)+1
print("Vocab_size :",vocab_size)

Vocab_size : 1


## ANN ALGORITHM


In [ ]:
import keras

In [ ]:
from keras.preprocessing.sequence import pad_sequences

In [ ]:
text = ['Mary moved to the bathroom . Sandra journeyed to the bedroom .']

In [ ]:
tokenizer = Tokenizer(num_words=18)

In [ ]:
tokenizer.fit_on_texts(text)

In [ ]:
sequences = tokenizer.texts_to_sequences(text)

In [ ]:
tokenizer=Tokenizer(filters=[])
tokenizer.fit_on_texts(vocab)
vocab_size = len(tokenizer.word_index) + 1
print("Corrected Vocab size:", vocab_size)

Corrected Vocab size: 38


In [ ]:
tokenizer.word_index

{'daniel': 1,
 'left': 2,
 'no': 3,
 'down': 4,
 'to': 5,
 'john': 6,
 'yes': 7,
 'moved': 8,
 'hallway': 9,
 'put': 10,
 'went': 11,
 'sandra': 12,
 'office': 13,
 'got': 14,
 'in': 15,
 'took': 16,
 'bedroom': 17,
 'discarded': 18,
 'mary': 19,
 'garden': 20,
 'kitchen': 21,
 'there': 22,
 'apple': 23,
 'milk': 24,
 'journeyed': 25,
 'dropped': 26,
 'grabbed': 27,
 'picked': 28,
 'travelled': 29,
 'back': 30,
 'football': 31,
 'up': 32,
 'the': 33,
 'bathroom': 34,
 'is': 35,
 '?': 36,
 '.': 37}

In [ ]:
train_story_text=[]
train_question_text=[]
train_answer=[]

for story, question, answer in train_data:
  train_story_text.append(story)
  train_question_text.append(question)
train_story_seq=tokenizer.texts_to_sequences(train_story_text)
len(train_story_text)

10000

In [ ]:
len(train_story_seq)

10000

In [ ]:
def vectorize_stories(data, word_index=tokenizer.word_index, max_story_len=max_story_len, max_question_len=max_question_len):
  X = []
  Xq = []
  Y = []
  for story, query, answer in data:
    if '<unk>' not in word_index:
      word_index['<unk>'] = len(word_index) + 1

    x=[word_index.get(word.lower(),word_index['<unk>']) for word in story]
    xq=[word_index.get(word.lower(),word_index['<unk>']) for word in query]
    y=np.zeros(len(word_index)+1)
    y[word_index[answer]]=1

    X.append(x)
    Xq.append(xq)
    Y.append(y)
  return (pad_sequences(X,maxlen=max_story_len),
          pad_sequences(Xq,maxlen=max_question_len),
          np.array(Y))

In [ ]:
inputs_train, queries_train, answers_train = vectorize_stories(train_data)

In [ ]:
inputs_train.shape

(10000, 156)

In [ ]:
queries_train.shape

(10000, 6)

In [ ]:
answers_train.shape

(10000, 39)

In [ ]:
inputs_test, queries_test, answers_test = vectorize_stories(test_data)

In [ ]:
inputs_test

array([[ 0,  0,  0, ..., 33, 17, 37],
       [ 0,  0,  0, ..., 33, 20, 37],
       [ 0,  0,  0, ..., 33, 20, 37],
       ...,
       [ 0,  0,  0, ..., 33, 23, 37],
       [ 0,  0,  0, ..., 33, 20, 37],
       [ 0,  0,  0, ..., 23, 22, 37]], dtype=int32)

In [ ]:
answers_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
sum(answers_test)

array([  0.,   0.,   0., 503.,   0.,   0.,   0., 497.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.])

In [ ]:
tokenizer.word_index['yes']

7

In [ ]:
tokenizer.word_index['no']

3

In [ ]:
from keras.models import Sequential,Model
from keras.layers import Embedding
from keras.layers import Input,Activation,Dense,Permute,Dropout
from keras.layers import add,dot,concatenate
from keras.layers import LSTM

In [ ]:
input_sequence=Input((max_story_len,))
question=Input((max_question_len,))

In [ ]:
input_encoder_m=Sequential()
input_encoder_m.add(Embedding(input_dim=vocab_size,output_dim=64))
input_encoder_m.add(Dropout(0.3))

In [ ]:
input_encoder_c=Sequential()
input_encoder_c.add(Embedding(input_dim=vocab_size,output_dim=max_question_len))
input_encoder_c.add(Dropout(0.3))

In [ ]:
question_encoder=Sequential()
question_encoder.add(Embedding(input_dim=vocab_size,output_dim=64,input_length=max_question_len))
question_encoder.add(Dropout(0.3))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [ ]:
input_encoded_m=input_encoder_m(input_sequence)
input_encoded_c=input_encoder_c(input_sequence)
question_encoded=question_encoder(question)

In [ ]:
match=dot([input_encoded_m,question_encoded],axes=(2,2))
match=Activation('softmax')(match)

In [ ]:
response=add([match,input_encoded_c])
response=Permute((2,1))(response)

In [ ]:
answer=Dropout(0.5)(concatenate([response,question_encoded]))
answer=LSTM(32)(answer)
answer=Dropout(0.5)(answer)
answer=Dense(vocab_size)(answer)

In [ ]:
answer=Activation('softmax')(answer)
model=Model([input_sequence,question],answer)
model.compile(loss='categorical_crossentropy',optimizer='rmsprop',metrics=['accuracy'])

In [ ]:
from tensorflow.keras.layers import Input,Dense,LSTM,Embedding,concatenate
from tensorflow.keras.models import Model
max_len_input=inputs_train.shape[1]
max_len_query=queries_train.shape[1]
input1=Input(shape=(max_len_input,))
x1=Embedding(vocab_size,64)(input1) # This will now use the corrected vocab_size
x1=LSTM(32)(x1)

In [ ]:
input2=Input(shape=(max_len_query,))
x2=Embedding(vocab_size,64)(input2) # This will now use the corrected vocab_size
x2=LSTM(32)(x2)

merged=concatenate([x1,x2])
output=Dense(vocab_size,activation='softmax')(merged) # Output layer size should also match vocab_size

model=Model(inputs=[input1,input2],outputs=output)

model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
model.summary()

Model: "functional_17"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer_23      │ (None, 156)       │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ input_layer_25      │ (None, 6)         │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ embedding_21        │ (None, 156, 64)   │      2,432 │ input_layer_23[0… │
│ (Embedding)         │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ embedding_23        │ (None, 6, 64)     │      2,432 │ input_layer_25[0… │
│ (Embedding)         │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ lstm_6 (LSTM)       │ (None, 32)        │     12,416 │ embedding_21[0][… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ lstm_8 (LSTM)       │ (None, 32)        │     12,416 │ embedding_23[0][… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ concatenate_5       │ (None, 64)        │          0 │ lstm_6[0][0],     │
│ (Concatenate)       │                   │            │ lstm_8[0][0]      │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_5 (Dense)     │ (None, 39)        │      2,535 │ concatenate_5[0]… │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 32,231 (125.90 KB)

 Trainable params: 32,231 (125.90 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
history=model.fit([inputs_train,queries_train],answers_train,batch_size=32,epochs=30,validation_data=([inputs_test,queries_test],answers_test))

Epoch 1/30
313/313 ━━━━━━━━━━━━━━━━━━━━ 32s 85ms/step - accuracy: 0.4989 - loss: 1.3317 - val_accuracy: 0.5030 - val_loss: 0.6952
Epoch 2/30
313/313 ━━━━━━━━━━━━━━━━━━━━ 24s 76ms/step - accuracy: 0.4917 - loss: 0.6971 - val_accuracy: 0.5030 - val_loss: 0.6950
Epoch 3/30
313/313 ━━━━━━━━━━━━━━━━━━━━ 41s 77ms/step - accuracy: 0.4969 - loss: 0.6970 - val_accuracy: 0.4970 - val_loss: 0.6940
Epoch 4/30
313/313 ━━━━━━━━━━━━━━━━━━━━ 25s 79ms/step - accuracy: 0.4983 - loss: 0.6960 - val_accuracy: 0.5030 - val_loss: 0.6945
Epoch 5/30
313/313 ━━━━━━━━━━━━━━━━━━━━ 25s 80ms/step - accuracy: 0.4897 - loss: 0.6981 - val_accuracy: 0.5030 - val_loss: 0.7131
Epoch 6/30
313/313 ━━━━━━━━━━━━━━━━━━━━ 41s 80ms/step - accuracy: 0.5095 - loss: 0.6981 - val_accuracy: 0.5030 - val_loss: 0.6952
Epoch 7/30
313/313 ━━━━━━━━━━━━━━━━━━━━ 26s 84ms/step - accuracy: 0.5017 - loss: 0.6959 - val_accuracy: 0.4970 - val_loss: 0.6940
Epoch 8/30
313/313 ━━━━━━━━━━━━━━━━━━━━ 26s 82ms/step - accuracy: 0.4969 - loss: 0.6948 - 

In [ ]:
filename='chatbot_120_epochs.keras'
model.save(filename)

In [ ]:
model.load_weights(filename)
pred_results=model.predict([inputs_test,queries_test])

32/32 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step


In [ ]:
story =' '.join(word for word in test_data[0][0])
print(story)

Mary got the milk there . John moved to the bedroom .


In [ ]:
query =' '.join(word for word in test_data[0][1])
print(query)

Is John in the kitchen ?


In [ ]:
print("True Test Answer from Data is: ",test_data[0][2])

True Test Answer from Data is:  no


In [ ]:
val_max=np.argmax(pred_results[0])

for key,val in tokenizer.word_index.items():
  if val==val_max:
    k=key

print("Predicted Answer is: ",k)
print("Probability of certainty was: ",pred_results[0][val_max])

Predicted Answer is:  yes
Probability of certainty was:  0.5208923


In [ ]:
my_story = 'John travelled the bathroom last saturday. Sandra dropped the football in the garden.'
my_story

'John travelled the bathroom last saturday. Sandra dropped the football in the garden.'

In [ ]:
my_question ="Did John travelled the bathroom last friday?"

In [ ]:
my_question.split()

['Did', 'John', 'travelled', 'the', 'bathroom', 'last', 'friday?']